name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out that no sensitive environment variable is shared
        run: env
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: run tests
        run: |
          tox -e build_docs

  codestyle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out that no sensitive environment variable is shared
        run: env
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: codestyle
        run: |
          tox -e codestyle
  CI:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.8
            toxenv: py38
          - os: windows-latest
            python-version: 3.8
            toxenv: py38
          - os: macos-latest
            python-version: 3.8
            toxenv: py38
          - os: ubuntu-latest
            python-version: 3.9
            toxenv: py39
          - os: windows-latest
            python-version: 3.9
            toxenv: py39
          - os: macos-latest
            python-version: 3.9
            toxenv: py39
          - os: ubuntu-latest
            python-version: 3.10
            toxenv: py310
          - os: windows-latest
            python-version: 3.10
            toxenv: py310
          - os: macos-latest
            python-version: 3.10
            toxenv: py310
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out that no sensitive environment variable is shared
        run: env
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Running tox
        run: |
          tox -e ${{ matrix.toxenv }}
  CI-Themes:
    runs-on: ${{ matrix.os }}
    needs: build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.9
            toxenv: sphinx_rtd_theme
          - os: ubuntu-latest
            python-version: 3.9
            toxenv: astropy_sphinx_theme
          - os: ubuntu-latest
            python-version: 3.9
            toxenv: alabaster
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check out that no sensitive environment variable is shared
        run: env
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Running tox
        run: |
          tox -e ${{ matrix.toxenv }}
